common/urls.py
from django.urls import include, path

from common import views

app_name = "common"
urlpatterns = [
    path("semester/", views.set_semester, name="set_semester"),
    path(
        "settings/",
        include(
            [
                path("edit/", views.edit_settings, name="edit_settings"),
            ],
        ),
    ),
]

rallyetool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import RedirectView

import common.views

urlpatterns = [
    # localization
    path("i18n/", include("django.conf.urls.i18n")),
    # common: choose semester and settings
    path("", include("common.urls")),
    # Ratings
    path("ratings/", include("ratings.urls")),
    path("r/", RedirectView.as_view(pattern_name="ratings:register_group")),
    path("register/", RedirectView.as_view(pattern_name="ratings:register_group")),
    # Challenges
    path("challenges/", include("challenges.urls")),
    # Admin
    path("admin/", admin.site.urls),
    # Index
    path("", RedirectView.as_view(pattern_name="ratings:main-view"), name="main-view"),
    # Map
    path("map/", RedirectView.as_view(pattern_name="ratings:overview-map"), name="overview-map"),
    path("m/", RedirectView.as_view(pattern_name="ratings:overview-map")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.USE_KEYCLOAK:
    urlpatterns += [
        # Auth
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("login/failed/", common.views.login_failed),
        path("logout/", RedirectView.as_view(pattern_name="oidc_logout"), name="logout"),
        path("login/", RedirectView.as_view(pattern_name="oidc_authentication_init"), name="login"),
    ]
else:
    urlpatterns += [
        # Auth
        path("login/", LoginView.as_view(template_name="registration/login.html"), name="login"),
        path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    ]

ratings/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic import RedirectView
from rest_framework import routers

from . import api, views

app_name = "ratings"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="ratings:view_leaderboard"), name="main-view"),
    path("dashboard/", RedirectView.as_view(pattern_name="ratings:view_leaderboard"), name="dashboard"),
    path("leaderboard/", views.leaderboard, name="view_leaderboard"),
    path("register/", views.register_group, name="register_group"),
    path(
        "station/",
        include(
            [
                path("", RedirectView.as_view(pattern_name="ratings:list_ratings"), name="rate-main_view"),
                path(
                    "rate/",
                    include(
                        [
                            path("list/", views.list_ratings, name="list_ratings"),
                            path("add/", views.add_rating, name="add_rating"),
                            path("edit/<int:rating_pk>/", views.edit_rating, name="edit_rating"),
                            path("del/<int:rating_pk>/", views.del_rating, name="del_rating"),
                        ],
                    ),
                ),
                path("rating-scheme/manage/", views.manage_rating_scheme, name="manage_rating_scheme"),
                path("view/<int:station_pk>/", views.view_station, name="view_station"),
                path(
                    "view/",
                    RedirectView.as_view(pattern_name="ratings:list_ratings"),
                    name="view_station-active_link",
                ),
            ],
        ),
    ),
    path(
        "administration/",
        include(
            [
                path(
                    "registration/<int:semester_pk>/<uuid:registration_uuid>",
                    views.register_user,
                    name="register_user",
                ),
                path(
                    "station/",
                    include(
                        [
                            path("import/", views.import_stations, name="import_stations"),
                            path("export/", views.export_stations, name="export_stations"),
                            path("sanitise/", views.sanitise_stations, name="sanitise_stations"),
                            path("list/", views.list_stations, name="list_stations"),
                            path("add/", views.add_station, name="add_station"),
                            path("edit/<int:station_pk>/", views.edit_station, name="edit_station"),
                            path("del/<int:station_pk>/", views.del_station, name="del_station"),
                        ],
                    ),
                ),
            ],
        ),
    ),
    path("map/", views.overview_map, name="overview-map"),
]
if settings.API:
    router = routers.DefaultRouter()
    router.register(r"teams", api.TeamsViewSet, basename="Group")
    urlpatterns += [
        # api
        path("api/", include(router.urls)),
        path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    ]

ratings/views.py
from typing import Any, Callable, Union
from uuid import UUID

from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.handlers.wsgi import WSGIRequest
from django.db import IntegrityError
from django.db.models import ProtectedError, QuerySet
from django.forms import forms, formset_factory
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _

from common.forms import NewTutorForm
from common.models import get_semester, Semester, Settings
from common.views import AuthWSGIRequest, rallye_login_required, superuser_required

from .forms import (
    EditRatingForm,
    EditStationForm,
    GroupForm,
    JsonStationUpdateForm,
    Rating1Form,
    Rating2Form,
    Rating3Form,
    RatingScheme2Form,
    RatingScheme3GroupForm,
    StationForm,
)
from .models import Group, Rating, RatingScheme3, RatingScheme3Group, RegistrationToken, Station

user_has_stand_required: Callable = user_passes_test(lambda u: bool(u.station))  # type: ignore


def register_group(request: WSGIRequest) -> HttpResponse:
    settings: Settings = Settings.load()
    if not settings.group_registration_available:
        messages.error(
            request,
            _("Registration of new groups is closed. Contact the Organisers if you think this is a mistake."),
        )
        return redirect("main-view")
    semester: Semester = get_object_or_404(Semester, pk=get_semester(request))

    form = GroupForm(request.POST or None, semester=semester)
    if form.is_valid():
        group_name = form.cleaned_data["name"]
        poss_matching_groups = list(Group.objects.filter(name__iexact=group_name))
        if poss_matching_groups:
            if len(poss_matching_groups) > 1:
                similar_groups = str(group.name for group in poss_matching_groups)
            else:
                similar_groups = poss_matching_groups[0].name
            messages.error(
                request,
                _(
                    "Registration of group '{group_name}' failed. "
                    "A group with a very similar name already exists. "
                    "The contender is: {similar_groups}",
                ).format(
                    {"group_name": group_name, "similar_groups": similar_groups},
                ),
            )
            return redirect("ratings:register_group")
        group: Group = form.save()
        messages.success(request, _("Registration of group '{}' successful.").format(group.name))
        return redirect("main-view")
    if request.POST:
        messages.error(request, _("Unsuccessful registration. Invalid information."))

    return render(request=request, template_name="registration/register_group.html", context={"form": form})


def leaderboard(request: WSGIRequest) -> HttpResponse:
    semester: Semester = get_object_or_404(Semester, pk=get_semester(request))
    groups = list(Group.objects.filter(semester=semester).order_by("total_points").reverse())
    place_and_groups = []
    if groups:
        first = groups.pop(0)
        place_and_groups.append((1, first))

        previous_min = first.total_points
        last_printed_place = 1
        for counter, group in enumerate(groups):
            if group.total_points < previous_min:
                # +2 because of 0 based index and because we have popped one already
                place_and_groups.append((counter + 2, group))
                last_printed_place = counter + 2
                previous_min = group.total_points
            else:
                place_and_groups.append((last_printed_place, group))

    context = {"place_and_groups": place_and_groups}
    return render(request, "ratings/leaderboard.html", context)


@rallye_login_required
@user_has_stand_required
def list_ratings(request: AuthWSGIRequest) -> HttpResponse:
    settings: Settings = Settings.load()
    if not settings.station_rating_avialible:
        messages.error(request, _("The organisers have ended this event."))
    station: Station = request.user.station
    ratings: QuerySet[Rating] = Rating.objects.filter(station=station).all()

    context = {"ratings": ratings, "station": station}
    return render(request, "ratings/rating/list_ratings.html", context)


@rallye_login_required
@user_has_stand_required
def add_rating(request: AuthWSGIRequest) -> HttpResponse:
    settings: Settings = Settings.load()
    if not settings.station_rating_avialible:
        messages.error(request, _("Unable to add a Rating. The organisers have ended this event."))
        return redirect("main-view")

    station = request.user.station

    form_lut = {2: Rating2Form, 3: Rating3Form}
    form_class = form_lut.get(station.rating_scheme_choices, Rating1Form)
    form = form_class(request.POST or None, station=station, semester=get_semester(request))

    if request.POST and form.is_valid():
        rating: Rating = form.save()
        messages.success(request, _("Rating {} was successfully added").format(rating))
        return redirect("ratings:list_ratings")

    context = {"form": form}

    return render(request, "ratings/rating/add_rating.html", context)


@rallye_login_required
@user_has_stand_required
def edit_rating(request: AuthWSGIRequest, rating_pk: int) -> HttpResponse:
    settings: Settings = Settings.load()
    if not settings.station_rating_avialible:
        messages.error(request, _("Unable to edit a Rating. The organisers have ended this event."))
        return redirect("main-view")
    rating = get_object_or_404(Rating, pk=rating_pk)
    form = EditRatingForm(request.POST or None, instance=rating)
    if request.POST and form.is_valid():
        form.save()
        messages.success(request, _("Rating {} was successfully edited").format(rating))
        return redirect("ratings:list_ratings")

    context = {"form": form, "rating": rating}

    return render(request, "ratings/rating/edit_rating.html", context)


@rallye_login_required
@user_has_stand_required
def del_rating(request: AuthWSGIRequest, rating_pk: int) -> HttpResponse:
    settings: Settings = Settings.load()
    if not settings.station_rating_avialible:
        messages.error(request, _("Unable to delete a Rating. The organisers have ended this event."))
        return redirect("main-view")
    rating: Rating = get_object_or_404(Rating, pk=rating_pk)

    if request.user.station != rating.station:
        return HttpResponseForbidden(_("You cant delete ratings of stations that are not your own"))

    form = forms.Form(request.POST or None)
    if form.is_valid():
        rating.delete()
        messages.success(request, _("Rating {} was permanently deleted.").format(rating))
        return redirect("ratings:list_ratings")
    messages.warning(request, _("Deletion is permanent."))
    context = {"form": form, "rating": rating}
    return render(request, "ratings/rating/del_rating.html", context)


@superuser_required
def list_stations(request: AuthWSGIRequest) -> HttpResponse:
    stations: QuerySet[Station] = Station.objects.all()
    context: dict[str, Union[str, QuerySet[Station]]] = {"stations": stations}
    settings: Settings = Settings.load()
    if settings.station_registration_availible:
        semester_pk: int = get_semester(request)
        registration_token: RegistrationToken = get_object_or_404(RegistrationToken, semester=semester_pk)
        link = reverse(
            "ratings:register_user",
            kwargs={
                "registration_uuid": registration_token.uuid,
                "semester_pk": semester_pk,
            },
        )
        context["registration_link"] = request.build_absolute_uri(link)
    return render(request, "ratings/administration/list_stations.html", context)


@superuser_required
def add_station(request: AuthWSGIRequest) -> HttpResponse:
    form = StationForm(request.POST or None)
    if form.is_valid():
        station: Station = form.save()
        messages.success(request, _("Station {} was successfully added.").format(station))
        return redirect("ratings:list_stations")
    context = {"form": form}
    return render(request, "ratings/administration/add_station.html", context)


@superuser_required
def edit_station(request: AuthWSGIRequest, station_pk: int) -> HttpResponse:
    station: Station = get_object_or_404(Station, pk=station_pk)

    form = EditStationForm(request.POST or None, instance=station)
    if form.is_valid():
        form.save()
        messages.success(request, _("Station {} was successfully edited.").format(station))
        return redirect("ratings:list_stations")
    messages.info(
        request,
        _(
            "If you want to increment the rating-scheme, make sure that no prior ratings exist. "
            "(highter number schemes require more information)",
        ),
    )
    context = {"form": form, "station": station}
    return render(request, "ratings/administration/edit_station.html", context)


@superuser_required
def sanitise_stations(request: AuthWSGIRequest) -> HttpResponse:
    stations: list[Station] = list(Station.objects.exclude(user=None).all())

    form = forms.Form(request.POST or None)
    if form.is_valid():
        for station in stations:
            station.user = None
            station.save()

        messages.success(
            request,
            _("The users of the stations {} have been permanently removed from their stations.").format(
                stations,
            ),
        )
        return redirect("ratings:list_stations")
    messages.warning(
        request,
        _("Removing people from their stations is permanent. Manually re-adding them is tedious."),
    )
    context = {"form": form, "stations": stations}

ratings/templates/ratings/rating/add_rating.html
{% extends "ratings/base_ratings.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block rallye_common_headercontent %}{% trans "Add rating" %}{% endblock %}

{% block rallye_common_content %}
<form
    method="post"
    action=""
>
    {% csrf_token %}
    {% bootstrap_form form %}

    <a
        class="btn btn-secondary"
        href="{% url "ratings:list_ratings" %}"
    >{% trans "Cancel" %}</a>
    <button
        class="btn btn-primary"
        type="submit"
    >{% trans "Add rating" %}</button>
</form>
{% endblock %}

ratings/templates/ratings/rating/del_rating.html
{% extends "ratings/base_ratings.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block rallye_common_headercontent %}
{% blocktrans trimmed %}
Delete rating {{ rating }}
{% endblocktrans %}
{% endblock %}

{% block rallye_common_content %}
<form
    method="post"
    action=""
>
    {% csrf_token %}

    <div class="row">
        <div class="col-xs-12 col-lg-5">
            {% bootstrap_form form %}
        </div>
    </div>

    <a
        class="btn btn-secondary"
        href="{% url "ratings:list_ratings" %}"
    >{% trans "Cancel" %}</a>
    <button
        class="btn btn-danger"
        type="submit"
    >{% trans "Delete rating" %}</button>
</form>
{% endblock %}

ratings/templates/ratings/rating/edit_rating.html
{% extends "ratings/base_ratings.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block rallye_common_headercontent %}
{% blocktrans trimmed %}
Edit rating {{ rating }}
{% endblocktrans %}
{% endblock %}

{% block rallye_common_content %}
<form
    method="post"
    action=""
>
    {% csrf_token %}

    <div class="row">
        <div class="col-xs-12 col-lg-5">
            {% bootstrap_form form %}
        </div>
    </div>

    <a
        class="btn btn-secondary"
        href="{% url "ratings:list_ratings" %}"
    >{% trans "Cancel" %}</a>
    <button
        class="btn btn-warning"
        type="submit"
    >{% trans "Edit rating" %}</button>
</form>
{% endblock %}

ratings/templates/ratings/rating/list_ratings.html
{% extends "ratings/base_ratings.html" %}
{% load django_bootstrap5 %}
{% load i18n %}


{% block head %}
<script>
    $(() => {
        $('#ratingsTable').DataTable({
            columnDefs: [{ targets: {{ station.rating_scheme_choices|add:2 }}, orderable: false }],
        });
    });
</script>
{% endblock %}

{% block rallye_common_headercontent %}
{% blocktrans trimmed %}
List all rating by station {{ station }}
{% endblocktrans %}
{% endblock %}

{% block rallye_common_content %}
{% if settings.station_rating_avialible %}
<div class='col-sm p-1 d-grid mb-4'>
    <a
        class="btn btn-lg btn-block btn-primary"
        href="{% url "ratings:add_rating" %}"
    >
        <span class="bi bi-plus"> {% trans "Add new Rating" %}</span>
    </a>
</div>
{% endif %}
{% if ratings %}
<div class="table-responsive">
    <table
        class="table dataTable"
        id="ratingsTable"
    >
        <thead>
            <tr>
                <th>{% trans "Last Update" %}</th>
                <th>{% trans "Teamname" %}</th>
                {% if station.rating_scheme_choices == 2 or station.rating_scheme_choices == 3 %}
                <th>{% trans "Value" %}</th>
                {% endif %}
                {% if station.rating_scheme_choices == 3 %}
                <th>{% trans "Handicap" %}</th>
                {% endif %}
                <th>{% trans "Points awarded" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for rating in ratings %}
            <tr>
                <td data-sort="{{rating.updated_at|date:"c"}}">{{rating.updated_at|date:"H:i"}}</td>
                <td>{{rating.group.name}}</td>
                {% if station.rating_scheme_choices == 2 or station.rating_scheme_choices == 3 %}
                <td>{{rating.value}}</td>
                {% endif %}
                {% if station.rating_scheme_choices == 3 %}
                <td>{{rating.handicap}}</td>
                {% endif %}
                <td>{{rating.points}}</td>
                <td>
                    <a
                        class="btn btn-warning"
                        href="{% url "ratings:edit_rating" rating.pk %}"
                    ><span class="bi bi-pencil-fill"></span> {% trans "Edit" %}</a>
                    <a
                        class="btn btn-danger"
                        href="{% url "ratings:del_rating" rating.pk %}"
                    ><span class="bi bi-trash-fill"></span> {% trans "Delete" %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p class="text-muted">{% trans "No ratings yet." %}</p>
{% endif %}
{% endblock %}