common/urls.py
from django.urls import include, path

from common import views

app_name = "common"
urlpatterns = [
    path("semester/", views.set_semester, name="set_semester"),
    path(
        "settings/",
        include(
            [
                path("edit/", views.edit_settings, name="edit_settings"),
            ],
        ),
    ),
]

rallyetool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import RedirectView

import common.views

urlpatterns = [
    # localization
    path("i18n/", include("django.conf.urls.i18n")),
    # common: choose semester and settings
    path("", include("common.urls")),
    # Ratings
    path("ratings/", include("ratings.urls")),
    path("r/", RedirectView.as_view(pattern_name="ratings:register_group")),
    path("register/", RedirectView.as_view(pattern_name="ratings:register_group")),
    # Challenges
    path("challenges/", include("challenges.urls")),
    # Admin
    path("admin/", admin.site.urls),
    # Index
    path("", RedirectView.as_view(pattern_name="ratings:main-view"), name="main-view"),
    # Map
    path("map/", RedirectView.as_view(pattern_name="ratings:overview-map"), name="overview-map"),
    path("m/", RedirectView.as_view(pattern_name="ratings:overview-map")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.USE_KEYCLOAK:
    urlpatterns += [
        # Auth
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("login/failed/", common.views.login_failed),
        path("logout/", RedirectView.as_view(pattern_name="oidc_logout"), name="logout"),
        path("login/", RedirectView.as_view(pattern_name="oidc_authentication_init"), name="login"),
    ]
else:
    urlpatterns += [
        # Auth
        path("login/", LoginView.as_view(template_name="registration/login.html"), name="login"),
        path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    ]

templates/base.html
{% load auth_method %}
{% load settings %}
{% load titles %}
{% load active_link_tags %}
{% load static %}
{% load i18n %}
{% load django_bootstrap5 %}
{% load semester %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
{% get_settings as settings %}
{% get_keycloak_status as keycloak_status %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="UTF-8">
    <meta
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
        name="viewport"
    >
    {% include "snippets/favoticons.html" %}
    <link
        href='{% static "bootstrap/dist/css/bootstrap.min.css" %}'
        rel='stylesheet'
    >
    <link
        href='{% static "bootstrap-icons/font/bootstrap-icons.css" %}'
        rel='stylesheet'
    >

    <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
    <script
        defer
        src="{% static "bootstrap/dist/js/bootstrap.bundle.min.js" %}"
    ></script>
    {% if user.is_authenticated %}
    <link
        href='{% static "choices.js/public/assets/styles/choices.min.css" %}'
        rel='stylesheet'
    />
    <script src='{% static "choices.js/public/assets/scripts/choices.min.js" %}'></script>
    {% endif %}
    <link
        href='{% static "css/style.css" %}'
        rel='stylesheet'
    >
    <link
        href='{% static "datatables.net-bs5/css/dataTables.bootstrap5.min.css" %}'
        rel='stylesheet'
    >
    <script
        defer
        src="{% static "datatables.net/js/jquery.dataTables.min.js" %}"
    ></script>
    <script
        defer
        src="{% static "datatables.net-bs5/js/dataTables.bootstrap5.min.js" %}"
    ></script>

    <title>{% random_title %}</title>

    {% block head %}{% endblock %}
    {% block extrahead %} {# Extra Resources Start #}
    {{ form.media }} {# Form required JS and CSS #}
    {% endblock %} {# Extra Resources End #}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-dark bg-dark mb-4">
            <div class="container-fluid">
                <a
                    class="navbar-brand"
                    href={% url "main-view" %}
                >
                    <span class="bi bi-signpost-2"></span> Rallyetool
                </a>
                {# button to show menu on small devices#}
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                    class="collapse navbar-collapse"
                    id="navbarNav"
                >
                    {# links to the apps' index pages #}
                    <nav class="navbar-nav me-auto mb-2 mb-lg-0">
                        <a
                            class="nav-link {% active_link "ratings:view_leaderboard" %}"
                            href="{% url "ratings:view_leaderboard" %}"
                        >{% trans "Leaderboard" %}</a>
                        {% if settings.group_registration_available %}
                        <a
                            class="nav-link {% active_link "ratings:register_group" %}"
                            href="{% url "ratings:register_group" %}"
                        >{% trans "Register Team" %}</a>
                        {% endif %}
                        <a
                            class="nav-link {% active_link "ratings:overview-map" %}"
                            href="{% url "overview-map" %}"
                        >{% trans "Map" %}</a>
                        {% if settings.scavenger_hunt_station and settings.scavenger_hunt_secret %}
                        <a
                            class="nav-link {% active_link "challanges:scavenger_hunt" %}"
                            href="{% url "challanges:scavenger_hunt" %}"
                        >{% trans "Scavenger Hunt" %}</a>
                        {% endif %}
                        {% if user.is_authenticated %}
                        {% if user.station %}
                        <a
                            class="nav-link {% active_link "ratings:rate-main_view" %}"
                            href="{% url "ratings:rate-main_view" %}"
                        >{% trans "Rate" %}</a>
                        {% endif %}
                        {% if user.is_superuser %}
                        <a
                            class="nav-link {% active_link "ratings:list_stations" %}"
                            href="{% url "ratings:list_stations" %}"
                        >{% trans "Administration" %}</a>
                        <a
                            class="nav-link {% active_link "common:edit_settings" %}"
                            href="{% url "common:edit_settings" %}"
                        >{% trans "Settings" %}</a>
                        {% endif %}
                        {% endif %}
                    </nav>
                    <div class="d-flex">

                        <nav class="navbar-nav me-2">
                            {# choose semester #}
                            {% if user.is_authenticated %}
                            <form
                                action="{% url "common:set_semester" %}"
                                method="post"
                                role="form"
                            >
                                <div>
                                    {% csrf_token %}
                                    <input
                                        name="next"
                                        type="hidden"
                                        value=""
                                    />

                                    <select
                                        class="form-control no-automatic-choicejs"
                                        name="semester"
                                        id="semester_selection_form"
                                        onchange="this.form.submit()"
                                    >
                                        {% get_semester as SEMESTER_PK %}
                                        {% get_available_semesters as semesters %}
                                        {% for semester in semesters %}
                                        <option
                                            value="{{ semester.pk }}"
                                            {% if semester.pk == SEMESTER_PK %}selected="selected"
                                            {% endif %}
                                        >
                                            {{ semester }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                    <label
                                        for="semester_selection_form"
                                        style="display: none;"
                                    >{% trans "Select your semester" %}</label>
                                </div>
                                <noscript>
                                    <button
                                        type="submit"
                                        class="btn btn-secondary"
                                    >{% trans "Switch semester" %}</button>
                                </noscript>
                            </form>
                            {% endif %}
                            {# end choose semester #}
                            {# login #}
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{% url "logout" %}"
                                >
                                    {# provide a Useful name, even if the User has not specified his first name #}
                                    {% if user.first_name %}
                                    {% blocktranslate trimmed with username=user.first_name|capfirst %}
                                    Log out {{ username }}
                                    {% endblocktranslate %}
                                    {% else %}
                                    {% blocktranslate trimmed with username=user.username|capfirst %}
                                    Log out {{ username }}
                                    {% endblocktranslate %}
                                    {% endif %}
                                </a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{% if keycloak_status %}{% url "oidc_authentication_init" %}{% else %}{% url "login" %}{% endif %}"
                                >{% trans "Login" %}</a>
                            </li>
                            {% endif %}
                            {# end login #}
                            {# language chooser #}
                            <li class="nav-item dropdown">
                                <a
                                    aria-expanded="false"
                                    class="dropdown-toggle nav-link"
                                    data-bs-toggle="dropdown"
                                    type="button"
                                >
                                    <span class="bi bi-globe"></span>
                                </a>
                                <form
                                    action="{% url "set_language" %}"
                                    aria-labelledby="languageDropdown"
                                    class="dropdown-menu dropdown-menu-end"
                                    method="post"
                                >
                                    {% csrf_token %}

                                    {% for language in languages %}
                                    <button
                                        name="language"
                                        class="dropdown-item {% if language.code == LANGUAGE_CODE %} active{% endif %}"
                                        type="submit"
                                        value="{{ language.code }}"
                                    >
                                        {{ language.name_local }}
                                    </button>
                                    {% endfor %}
                                </form>
                            </li>
                            {# end language chooser #}
                        </nav>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main
        role="main"
        class="container-fluid"
    >
        {% bootstrap_messages %}

        {% block content %}{% endblock %}
    </main>
    {% block after_content %}{% endblock %}
    <footer class="footer navbar navbar-expand navbar-dark bg-dark">
        <div class="container-md">
            <ul class="navbar-nav text-nowrap overflow-auto mx-auto">
                <li class="nav-item">
                    <a
                        class="nav-link"
                        href="https://fs.tum.de/datenschutz/rallye.mpi.fs.tum.de/"
                    >{% trans "Data protection" %}</a>
                </li>
                <li class="nav-item">
                    <a
                        class="nav-link"
                        href="https://github.com/FSTUM/rallyetool-v2"
                    ><span class="bi bi-github"></span></a>
                </li>
                <li class="nav-item">
                    <a
                        class="nav-link"
                        href="https://fs.tum.de/impressum/"
                    >{% trans "Imprint" %}</a>
                </li>
            </ul>
        </div>
    </footer>

    <script type="text/javascript">
    /* global Choices */
    /* eslint no-new: off */
    const elemnts = document.getElementsByTagName('select');
    for (let i = 0; i < elemnts.length; i += 1) {
        if (!elemnts[i].classList.contains('no-automatic-choicejs'))
            new Choices(elemnts[i], { removeItemButton: true });
    }
    </script>
    {% block defered_script %} {% endblock %}
</body>

</html>

templates/base_card_layout.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}

{% block navigation-override-1 %}
<div class="row">
    <div class="col-lg-3 col-xl-2 mb-4">
        <div class="card">
            <div class="card-header">
                {% trans "Navigation" %}
            </div>
            <div class="card-body">
                <nav class="nav flex-column nav-pills">
                    {% block rallye_common_navigation %}{% endblock %}
                </nav>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-xl-10">
        {% endblock %}
        <div class="card">
            <div class="card-header">
                {% block rallye_common_headercontent %}{% endblock %}
            </div>
            <div
                class="card-body"
                {% block rallye_card-body-override %}{% endblock %}
            >
                {% block rallye_common_content %}{% endblock %}
            </div>
        </div>
        {% block navigation-override-2 %}
    </div>
</div>
{% endblock %}
{% endblock %}

templates/base_single_card_layout.html
{% extends "base_card_layout.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        {% block rallye_common_headercontent %}{% endblock %}
    </div>
    <div
        class="card-body"
        {% block rallye_card-body-override %}{% endblock %}
    >
        {% block rallye_common_content %}{% endblock %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}

<div class="container">
    <h1>{% trans "Wellcome to the Ralleytool" %}</h1>
    <form
        action="{% url "login" %}"
        method="POST"
        accept-charset="utf-8"
        role="form"
    >{% csrf_token %}
        {% bootstrap_form form layout="floating" %}

        <input
            type="hidden"
            name="next"
            value="{{ next }}"
        />
        <button
            class="btn btn-primary"
            type="submit"
        >Login <span class="bi bi-box-arrow-in-right"></span></button>
    </form>
</div>
{% endblock %}